# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('youtube', ['internet', 'config-store', 'applications'])
    module.source = [
        'model/youtube-client.cc',
        'model/youtube-server.cc',
        'model/youtube-controller.cc',
        'helper/youtube-helper.cc',
        ]
        
    module_test  = bld.create_ns3_module_test_library('youtube')
    module_test .source = [ ]
        
    headers = bld(features='ns3header')
    headers.module = 'youtube'
    headers.source = [
        'model/youtube-client.h',
        'model/youtube-server.h',
        'model/youtube-controller.h',
        'helper/youtube-helper.h',
        ]

    if (bld.env['ENABLE_EXAMPLES']):
      bld.recurse('examples')

      
      #bld.ns3_python_bindings()
